# GGMCore 플러그인 설정 파일

# 데이터베이스 설정
database:
  host: "localhost"
  port: 3306
  database: "ggm_server"
  username: "root"
  password: "1224"

# G 시스템 설정
economy:
  # 송금 수수료 (10% = 0.1)
  transfer_fee: 0.1
  # 신규 플레이어 시작 G
  starting_money: 1000
  # 최대 송금 가능 금액
  max_transfer: 100000000

# 크로스 서버 인벤토리 동기화 설정
inventory_sync:
  enabled: true                    # 인벤토리 동기화 사용 여부
  save_on_quit: true              # 서버 퇴장 시 자동 저장
  load_on_join: true              # 서버 접속 시 자동 로드
  load_delay: 20                  # 로드 지연 시간 (틱, 20 = 1초)
  sync_health: false               # 체력 동기화
  sync_hunger: false               # 배고픔 동기화
  sync_experience: true           # 일반 경험치 동기화 (인첸트용)
  backup_on_save: false           # 저장 시 백업 생성 (개발용)

# 직업 경험치 시스템 설정 (NEW!)
job_experience:
  enabled: true                   # 직업 경험치 시스템 사용 여부
  
  # 레벨업 필요 경험치 (커스터마이징 가능)
  level_requirements:
    1: 0      # 1레벨은 0 경험치
    2: 100    # 2레벨: 100 경험치
    3: 300    # 3레벨: 총 300 경험치
    4: 600    # 4레벨: 총 600 경험치
    5: 1000   # 5레벨: 총 1000 경험치
    6: 1500   # 6레벨: 총 1500 경험치
    7: 2100   # 7레벨: 총 2100 경험치
    8: 2800   # 8레벨: 총 2800 경험치
    9: 3600   # 9레벨: 총 3600 경험치
    10: 5000  # 10레벨(만렙): 총 5000 경험치
  
  # 직업별 경험치 획득 배율
  job_multipliers:
    # 탱커 (방어 관련)
    TANK:
      DAMAGE_TAKEN: 2       # 피해 받을 때
      BLOCK_WITH_SHIELD: 5  # 방패로 막을 때
      KILL_MONSTER: 3       # 몬스터 처치
    
    # 검사 (근접 전투)
    WARRIOR:
      MELEE_KILL: 4         # 근접 무기로 처치
      CRITICAL_HIT: 3       # 크리티컬 히트
      SWORD_DAMAGE: 2       # 검으로 피해 입힐 때
    
    # 궁수 (원거리 전투)
    ARCHER:
      BOW_KILL: 5           # 활로 처치
      LONG_SHOT: 7          # 장거리 사격 (30블록 이상)
      HEADSHOT: 10          # 헤드샷 (크리티컬)
    
    # 광부 (채굴)
    MINER:
      MINE_ORE: 3           # 일반 광석 채굴
      MINE_RARE_ORE: 8      # 희귀 광석 채굴 (다이아, 에메랄드)
      MINE_STONE: 1         # 돌 채굴
    
    # 나무꾼 (벌목)
    LUMBERJACK:
      CUT_TREE: 2           # 일반 나무 벌목
      CUT_RARE_TREE: 5      # 희귀 나무 벌목 (정글, 다크오크)
    
    # 어부 (낚시)
    FISHER:
      CATCH_FISH: 3         # 물고기 낚기
      CATCH_TREASURE: 10    # 보물 낚기
      CATCH_JUNK: 1         # 쓰레기 낚기

  # 경험치 보너스 설정
  bonuses:
    weekend_multiplier: 1.5   # 주말 경험치 1.5배
    event_multiplier: 2.0     # 이벤트 시 경험치 2배
    party_bonus: 1.2          # 파티 플레이 시 20% 보너스

  # 알림 설정
  notifications:
    exp_gain_message: true    # 경험치 획득 메시지 표시
    levelup_sound: true       # 레벨업 사운드 재생
    levelup_effects: true     # 레벨업 파티클 효과
    broadcast_levelup: false  # 레벨업 시 전체 공지

# 커스텀 인첸트 설정
custom_enchants:
  # 기존 인첸트들
  lightning:
    base_chance: 5        # 기본 확률 5%
    chance_per_level: 5   # 레벨당 +5%
    max_chance: 25        # 최대 확률 25%

  auto_repair:
    base_chance: 3        # 기본 확률 3%
    chance_per_level: 3   # 레벨당 +3%
    max_chance: 15        # 최대 확률 15%

  vampire:
    heal_percentage: 10   # 피해량의 10%
    heal_per_level: 10    # 레벨당 +10%

  exp_boost:
    base_exp: 2           # 기본 경험치 +2 (일반 경험치용)
    exp_per_level: 2      # 레벨당 +2

  # 새로운 인첸트들
  explosive_arrow:
    base_power: 1.0       # 기본 폭발력
    power_per_level: 0.5  # 레벨당 폭발력 증가

  auto_smelt:
    bonus_chance: 10      # 추가 아이템 드롭 확률 (레벨당 %)

  area_mining:
    cooldown: 1000        # 쿨다운 (밀리초)
    durability_cost: 1    # 블록당 내구도 소모

  poison_blade:
    duration: 100         # 독 지속시간 (틱)
    duration_per_level: 20 # 레벨당 지속시간 증가

  freeze:
    duration: 60          # 빙결 지속시간 (틱)
    duration_per_level: 20 # 레벨당 지속시간 증가

  tree_feller:
    max_blocks: 64        # 최대 제거 블록 수

# 인첸트북 설정 (확장됨)
enchant_books:
  # 각 등급별 인첸트 풀 (바닐라 + 커스텀)
  common:
    - "DURABILITY:1"
    - "EFFICIENCY:1"
    - "UNBREAKING:1"
    - "SHARPNESS:1"
    - "PROTECTION:1"
    - "CUSTOM:auto_repair:1"        # 커스텀: 자동수리 1레벨
    - "CUSTOM:vampire:1"            # 커스텀: 흡혈 1레벨
    - "CUSTOM:exp_boost:1"          # 커스텀: 경험증폭 1레벨
    - "CUSTOM:high_jump:1"          # 커스텀: 점프 1레벨
    - "CUSTOM:auto_smelt:1"         # 커스텀: 자동제련 1레벨

  rare:
    - "EFFICIENCY:2"
    - "UNBREAKING:2"
    - "SHARPNESS:2"
    - "PROTECTION:2"
    - "FIRE_PROTECTION:1"
    - "PROJECTILE_PROTECTION:1"
    - "CUSTOM:vampire:2"            # 커스텀: 흡혈 2레벨
    - "CUSTOM:lightning:1"          # 커스텀: 번개 1레벨
    - "CUSTOM:poison_blade:1"       # 커스텀: 독날 1레벨
    - "CUSTOM:explosive_arrow:1"    # 커스텀: 폭발화살 1레벨
    - "CUSTOM:freeze:1"             # 커스텀: 빙결 1레벨
    - "CUSTOM:regeneration:1"       # 커스텀: 재생 1레벨

  epic:
    - "EFFICIENCY:3"
    - "UNBREAKING:3"
    - "SHARPNESS:3"
    - "PROTECTION:3"
    - "FIRE_PROTECTION:2"
    - "PROJECTILE_PROTECTION:2"
    - "FORTUNE:1"
    - "LOOTING:1"
    - "CUSTOM:lightning:2"          # 커스텀: 번개 2레벨
    - "CUSTOM:area_mining:1"        # 커스텀: 광역채굴 1레벨
    - "CUSTOM:tree_feller:1"        # 커스텀: 나무꾼 1레벨
    - "CUSTOM:freeze:2"             # 커스텀: 빙결 2레벨
    - "CUSTOM:regeneration:2"       # 커스텀: 재생 2레벨

  ultimate:
    - "EFFICIENCY:4"
    - "UNBREAKING:4"
    - "SHARPNESS:4"
    - "PROTECTION:4"
    - "FORTUNE:2"
    - "LOOTING:2"
    - "CUSTOM:lightning:3"          # 커스텀: 번개 3레벨
    - "CUSTOM:vampire:3"            # 커스텀: 흡혈 3레벨
    - "CUSTOM:area_mining:2"        # 커스텀: 광역채굴 2레벨
    - "CUSTOM:tree_feller:2"        # 커스텀: 나무꾼 2레벨
    - "CUSTOM:explosive_arrow:2"    # 커스텀: 폭발화살 2레벨
    - "CUSTOM:auto_smelt:2"         # 커스텀: 자동제련 2레벨

# 인첸트 제한 설정
enchant_restrictions:
  enabled: true
  
  # 아이템별 최대 인첸트 제한
  max_enchants_per_item:
    SWORD: 8
    BOW: 6
    TOOL: 7
    ARMOR: 6
    DEFAULT: 5

  # 인첸트 레벨 제한
  max_enchant_levels:
    SHARPNESS: 5
    PROTECTION: 4
    EFFICIENCY: 5
    UNBREAKING: 3
    FORTUNE: 3
    LOOTING: 3

# 파괴방지권 설정
protection_scroll:
  enabled: true
  success_rate: 70          # 기본 성공률 70%
  consume_on_failure: true  # 실패 시 파괴방지권 소모 여부

# 모루 인첸트 적용 설정
anvil_enchanting:
  enabled: true
  allow_custom_enchants: true     # 커스텀 인첸트 적용 허용
  experience_cost_multiplier: 1.0 # 경험치 비용 배율
  max_repair_cost: 39            # 최대 수리 비용

# 스코어보드 설정
scoreboard:
  enabled: true
  update_interval: 20     # 업데이트 간격 (틱)
  show_job_info: true     # 직업 정보 표시 (야생 서버만)
  show_job_exp: true      # 직업 경험치 표시 (야생 서버만)

# 액션바 설정
actionbar:
  enabled: true
  update_interval: 10     # 업데이트 간격 (틱)
  show_coordinates: true  # 좌표 표시
  show_direction: true    # 방향 표시